# Generated by Django 6.0.8 on 2026-08-05 08:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255, verbose_name='College Name')),
                ('college_code', models.CharField(max_length=50, unique=True, verbose_name='College Code')),
                ('contact_person', models.CharField(max_length=150, verbose_name='Contact Person')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR Secure Token')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code Image')),
                ('max_pass', models.PositiveIntegerField(default=2, verbose_name='Maximum Passes (Delegates)')),
                ('used_pass', models.PositiveIntegerField(default=0, verbose_name='Used Passes')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
