# Generated by Django 6.0.8 on 2026-08-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='college',
            name='phone',
        ),
    ]
