"""
Django settings for qr_pass_project project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


import dj_database_url

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-cdha68%r6*egb53&x)!d(6m@s%^!%m!w5h_*k1^m2bw!f*g*_a')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')

ALLOWED_HOSTS = ['.vercel.app', '127.0.0.1', 'localhost', '*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.vercel.app',
    'http://127.0.0.1',
    'http://localhost',
]




# Application definition

INSTALLED_APPS = [
    'daphne',  # Daphne must be loaded before django.contrib.staticfiles for ASGI development support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions', 
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'accounts',
    'colleges',
    'scanner',
    'dashboard',
    'reports',
    'api',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AuditLogMiddleware',  # Custom audit logging middleware
]

ROOT_URLCONF = 'qr_pass_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qr_pass_project.wsgi.application'
ASGI_APPLICATION = 'qr_pass_project.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# """DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'railway',
#         'USER': 'root',
#         'PASSWORD': 'lYmfhOcyDIIKxOhjDImaGYGArRTQEFqQ',
#         'HOST': 'altaria.proxy.rlwy.net',
#         'PORT': '32034',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#             'charset': 'utf8mb4',
#         }
#     }
# }"""


DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=0,
            conn_health_checks=False,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'scan_db',
            'USER': 'postgres',
            'PASSWORD': 'admin123',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }
    }

# Channel Layers for WebSockets
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}
 
# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (for saving uploaded Excel and generated QR code images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Site URL (Base domain, used for building absolute URLs for emails)
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')

# Email Config (Gmail SMTP Configuration)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'teamkdns19@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'rhwnvrldvjrmvhsh')
DEFAULT_FROM_EMAIL = '"REGIONAL AI SUMMIT 2.0" <teamkdns19@gmail.com>'

# Logo & Link Configs for the cold email template
SNR_LOGO_URL = "https://sriramakrishna.com/wp-content/uploads/2024/09/SNR.png.png"
SRIT_LOGO_URL = "https://media.canva.com/v2/image-resize/format:PNG/height:285/quality:100/uri:ifs%3A%2F%2FM%2F4f84833d-30d1-493e-b6e6-f7c2f8b507ee/watermark:F/width:940?csig=AAAAAAAAAAAAAAAAAAAAAEACwmjE5JmHM_YEyZ4wFXe6qZbJ8M0vgKw95yUxvk0T&exp=1788859108&osig=AAAAAAAAAAAAAAAAAAAAAMXnNBZeWay8xfNq-Tq5llWvxryVfVzjSmo344i2v6Ga&signer=media-rpc&x-canva-quality=screen_3x"
RAS_LOGO_URL = "https://wonderful-malabi-521a08.netlify.app/ras2.0_logo.png"
YUVAASOFT_LOGO_URL = "https://www.yuvaasoft.com/static/image/yuvaasoft_logo.png"
REGISTRATION_URL = "https://www.regionalaisummit.com/registration"
VISITOR_PASS_BROCHURE_URL = "https://wonderful-malabi-521a08.netlify.app/visitorpass_brochure.pdf"
RAS_BENEFITS_BROCHURE_URL = "https://www.regionalaisummit.com/static/site/pdf/ras2_participants_benefits.pdf"

# Event Details Config
EVENT_VENUE = "Sri Ramakrishna Institute Of Technology, Coimbatore"
EVENT_DATE = "September 24-26, 2026"

