# Generated by Django 6.0.8 on 2026-08-05 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_number', models.PositiveIntegerField(verbose_name='Scan Sequence Number')),
                ('scan_time', models.DateTimeField(auto_now_add=True, verbose_name='Scan Time')),
                ('scanner_device', models.CharField(max_length=255, verbose_name='Scanner Device/User-Agent')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Scan Location')),
                ('status', models.CharField(choices=[('Allowed', 'Allowed'), ('Denied', 'Denied')], max_length=20, verbose_name='Scan Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='colleges.college', verbose_name='College')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_logs', to=settings.AUTH_USER_MODEL, verbose_name='Scanned By')),
            ],
            options={
                'ordering': ['-scan_time'],
            },
        ),
    ]
